### ISSUE TITLE
データ更新の自動化

### ISSUE THREAD

**Issue by sunmoonStern** [code-for-future-moms/prototype-k#124]
- やり方考える
- スクレイピングはこのrepoでやっている https://github.com/code-for-future-moms/fetch-open-data
   - このスクリプトで https://github.com/code-for-future-moms/fetch-open-data/tree/main/information-extraction2
   - 集めたデータをここに置いている https://github.com/code-for-future-moms/fetch-open-data/tree/main/data
- fetch-open-dataのrepoで月1でスクレイピングして新しいデータを追加するPRを自動で作る? → prototype-k側の参照するデータを更新する修正PRは手動であげる?
   - prototype-k側の修正は1行なので https://github.com/code-for-future-moms/prototype-k/pull/119

**Comment by ktakayama** [comment]
公開リポジトリなので、GitHub Actions でやるのがコストかからなくて良さそうですね

内容被ってますが

## 案1
- code-for-future-moms/fetch-open-data のリポジトリ内の GitHub Actions でデータ更新&code-for-future-moms/prototype-k へのPR作成

## 案2
- code-for-future-moms/fetch-open-data のリポジトリ内の GitHub Actions でデータ更新
- code-for-future-moms/prototype-k のリポジトリ内の GitHub Actions で fetch-open-data 内のデータが更新されたかチェックして反映する

----

みたいなイメージ

後者のほうが疎結合感あって好きです

**Comment by sunmoonStern** [comment]
基本案２でいいと思うけど、prototype-kの方のPR作成は自動化してもしなくてもとは思う。
PR作成は自動だけど、レビューは人力とか、どこかで人間がチェックする仕組みを入れられたらと思う。

**Comment by sunmoonStern** [comment]
実装してある程度ローカルで動作確認してえいやでマージして動作確認中 https://github.com/code-for-future-moms/fetch-open-data/actions/runs/9082081181
業務ではGitHub Actionsを使っていないので細かいノウハウがあまりない 😓

**Comment by ktakayama** [comment]
この手のやつは、最初の成功させるまでがめんどうなんですよね〜

**Comment by sunmoonStern** [comment]
// 昼やすみなのでちょっとコメント
基本的に動いていて、権限がなくて最後にcommitしてpushできないようなので
workflowに書き込み権限与えるなりtokenを設定するなりが必要と思いますが、そのへんTakayamaさんがGitHub Actionsを普段使っていて、この実装そのまま参考にすればOKなどあれば、共有お願いできますでしょうか? 👀 
なかなかまとまった開発時間が取れなくて

**Comment by ktakayama** [comment]
すいません、全然見れてませんでした

**Comment by ktakayama** [comment]
個人で使っていて非公開リポジトリのものなのですが、バッチ処理&自動コミットはこれ使っています。動いてます。権限まわりは確かにハマりどころなんですが、これ特に記述なくて大丈夫ですね。なんでだったかな。

```yml
name: Generate-Post

on:
  schedule:
    # 10,14,15,17,19,23
    - cron: '10 1,5,6,8,10,14 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Check ruby
      run: ruby -v
    - name: Generate post
      run: |
        ruby bin/updater.rb
    - name: git setting
      run: |
        git config --local user.email "gthub-actions@github.com"
        git config --local user.name "github-actions"
    - name: Commit files
      run: |
        git add docs/_posts
        if ! git diff --exit-code --staged --quiet
        then
          git commit -m "Generate post" -a
          git push origin main
        fi
```
